[theme]
base = "dark"
primaryColor = "#F14A00"              # warna aksen utama (button, slider, dll.)
backgroundColor = "#2A004E"           # background utama
secondaryBackgroundColor = "#500073"  # background sidebar / container
textColor = "#F9FAFB"
font = "sans serif"
